version: '3'
services:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.2
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks: 
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.16.2
    ports: ['5601:5601']
    networks:
      - elastic
    links: ['elasticsearch']
    depends_on: ['elasticsearch']

networks:
  elastic:
    driver: bridge

volumes:
  data:
    driver: local
